#!/bin/bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MATH_HARD_MODEL_NAME=sdar
export MATH_HARD_MODEL_PATH="${MATH_HARD_MODEL_PATH:-models/SDAR-8B-Chat}"
export MATH_HARD_ALGORITHM=ebpo
export MATH_HARD_ENGINE="${MATH_HARD_ENGINE:-sglang}"
export MATH_HARD_EXPERIMENT_TAG=sdar_ebpo_math_hard
export MATH_HARD_MASK_TOKEN_ID=151669
export MATH_HARD_PAD_TOKEN_ID=151643
export MATH_HARD_WRAP_POLICY=sdar
export MATH_HARD_DATA_RETURN_RAW_CHAT=True
export MATH_HARD_MODEL_USE_REMOVE_PADDING=True
export MATH_HARD_MODEL_ATTN_IMPLEMENTATION=flash_attention_2
export MATH_HARD_ACTOR_PARAM_OFFLOAD=True
export MATH_HARD_ACTOR_OPTIMIZER_OFFLOAD=True
export MATH_HARD_REF_PARAM_OFFLOAD=True
export MATH_HARD_ULYSSES_SEQUENCE_PARALLEL_SIZE="${MATH_HARD_ULYSSES_SEQUENCE_PARALLEL_SIZE:-4}"
export MATH_HARD_PPO_MAX_TOKEN_LEN_PER_GPU="${MATH_HARD_PPO_MAX_TOKEN_LEN_PER_GPU:-4096}"
export MATH_HARD_TEMPERATURE=1.0
export MATH_HARD_BLOCK_LENGTH=4
export MATH_HARD_NUM_DIFFUSION_STEPS=4
export MATH_HARD_VAL_NUM_DIFFUSION_STEPS=4
export MATH_HARD_SET_MAX_NEW_TOKENS=True
export MATH_HARD_ROLLOUT_USE_CACHE=False

exec "${script_dir}/../math_hard/run_dllm_math_hard.sh" "$@"
